AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda function for running Lurk on a schedule

Resources:
  LurkLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/
      Handler: handler.handler
      Runtime: python3.13
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          LURK_CONFIG: /var/task/lurk.yaml
          LURK_TELEGRAM_TOKEN: "/lurk/telegram_token"
          LURK_TELEGRAM_CHAT_ID: "/lurk/telegram_chat_id"
      Policies:
        -  SSMParameterReadPolicy:
            ParameterName: "lurk/*"

      # Events:
      #   ScheduledEvent:
      #     Type: ScheduleV2
      #     Properties:
      #       Description: "Run lurk on a schedule"
      #       ScheduleExpression: rate(10 minutes)
      #       RetryPolicy:
      #           MaximumRetryAttempts: 5
